# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_drafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('timer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='send_mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('open_counter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('channels_subscribed', models.CharField(max_length=100)),
                ('administrator', models.CharField(max_length=100)),
            ],
        ),
    ]
