# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20180303_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='channels_subscribed',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('b', 'big')], max_length=1),
        ),
    ]
