# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20180303_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
