# Generated by Django 2.0.3 on 2018-03-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvimport', '0002_test_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.RemoveField(
            model_name='item',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='uom',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
    ]
